using System;using System.IO;using System.Drawing;using System.Reflection;using System.Windows.Forms;using FateLauncher;
public static class ExternalGuiChecks {
 static readonly BindingFlags flags=BindingFlags.Instance|BindingFlags.NonPublic;static int count;
 static object F(object o,string n){return o.GetType().GetField(n,flags).GetValue(o);}static void Check(bool b,string s){if(!b)throw new Exception(s);count++;Console.WriteLine("PASS "+s);}
 static void CheckLaunchStates(){var method=typeof(LauncherForm).GetMethod("ExternalLaunchMessage",BindingFlags.Static|BindingFlags.NonPublic);
  Check(((string)method.Invoke(null,new object[]{Json.Parse("{\"status\":\"running\"}")})).Contains("실행했습니다"),"running confirms launch without error field");
  Check(((string)method.Invoke(null,new object[]{Json.Parse("{\"status\":\"ready\"}")})).Contains("지연"),"ready timeout reports delay without error field");
  Check(((string)method.Invoke(null,new object[]{Json.Parse("{\"status\":\"exited\",\"error\":null}")})).Contains("종료"),"early emulator exit reported");
  foreach(string state in new[]{"error","io-error","unexpected"}){bool failed=false;try{method.Invoke(null,new object[]{Json.Parse("{\"status\":\""+state+"\",\"error\":\"test read failure\"}")});}catch(TargetInvocationException e){failed=e.InnerException.Message==(state=="unexpected"?"외부 로더 실행 응답 오류: unexpected":"test read failure");}Check(failed,state+" cannot report launch success");}
 }
 [STAThread]public static int Main(string[] a){try{CheckLaunchStates();Application.EnableVisualStyles();Directory.CreateDirectory(a[0]);using(var f=new LauncherForm(a[0],true)){f.ShowInTaskbar=false;f.Opacity=0;f.Show();Application.DoEvents();var mode=(ComboBox)F(f,"installMode");var box=(CheckBox)F(f,"baseBox");Check(mode.SelectedIndex==0,"existing ISO mode is default");mode.SelectedIndex=1;f.GetType().GetMethod("CaptureSettings",flags).Invoke(f,null);Check(((Settings)F(f,"config")).UseExternalData,"external mode captured");Check(((Label)F(f,"selectionSummary")).Text.Contains("원본 ISO"),"external source retention explained");using(var bitmap=new Bitmap(f.Width,f.Height)){f.DrawToBitmap(bitmap,new Rectangle(0,0,f.Width,f.Height));bitmap.Save(Path.Combine(a[0],"external-mode.png"));}box.Checked=false;Check(!mode.Enabled,"mode disabled without base installation");Check(!((Control)F(f,"source")).Enabled,"extras selection path scope preserved");box.Checked=true;mode.SelectedIndex=0;f.GetType().GetMethod("CaptureSettings",flags).Invoke(f,null);Check(!((Settings)F(f,"config")).UseExternalData,"switching back selects ISO installation");f.Close();}Json.Write(Path.Combine(a[0],"gui-checks.json"),new{status="PASS",assertions=count});return 0;}catch(Exception e){Console.Error.WriteLine(e);return 1;}}
}
