using System;using System.IO;using System.Linq;using System.Text.RegularExpressions;using System.Collections.Generic;using System.Reflection;using System.Threading;using FateLauncher;
public static class OptionalUiTests {
 static int count;static void Assert(bool ok,string label){if(!ok)throw new Exception(label);count++;Console.WriteLine("PASS "+label);}
 static void Reject(Action action,string part,string label){try{action();}catch(Exception e){Assert(e.Message.Contains(part),label+" ("+e.Message+")");return;}throw new Exception("Accepted "+label);}
 static string Setting(string s,string section,string key){bool inside=false;string v=null;foreach(string line in s.Split('\n')){var h=Regex.Match(line.Trim(),@"^\[(.*?)\]$");if(h.Success){inside=h.Groups[1].Value==section;continue;}if(inside&&Regex.IsMatch(line,@"^"+key+@"\s*="))v=line.Substring(line.IndexOf('=')+1).Trim();}return v;}
 [STAThread]public static void Main(string[] args){try{Run(args);}catch(Exception e){Console.Error.WriteLine(e);Environment.ExitCode=1;}}
 static void Run(string[] args){string w=args[0],assets=args[1],tools=Path.Combine(w,"build","tools");var r=ReleaseInfo.Read(File.ReadAllText(Path.Combine(assets,"launcher-update.json")),"v8e-ui-v1");
  if(args.Length>2&&args[2]=="public"){var pub=new Engine(new Settings{DataRoot=Path.Combine(w,"public-data")},Path.Combine(w,"public-settings.json"),tools).Latest();Assert(pub.UiVersion=="UI-v1"&&pub.HdVersion=="HD-v39"&&pub.Tag==r.Tag,"public feed offers independent HD and UI");Assert(pub.Ui.Size==r.Ui.Size&&pub.Ui.Hash==r.Ui.Hash,"public optional UI asset matches verified package");var e=new Engine(new Settings{DataRoot=Path.Combine(w,"public-download")},Path.Combine(w,"pd.json"),tools);string got=e.Download(pub.Ui,pub.Tag);Assert(Engine.Hash(got)==r.Ui.Hash,"fresh public optional UI download verified");Json.Write(Path.Combine(w,"public-feed-test.json"),new{status="PASS",tests=count});return;}
  Assert(!new Settings().SelectUI&&!new Settings().SelectHD,"new users opt in separately to HD and UI");Assert(r.UiVersion=="UI-v1"&&r.Ui!=null&&r.HdVersion=="HD-v39","separate component versions parse");
  string original="[General]\r\nEnableCheats = False\r\n[Graphics]\r\nInternalResolution = 2\r\nMultiSampleLevel = 0\r\nVerticalSync = False\r\nReplaceTextures = False\r\nRenderingMode = 9\r\n[Sound]\r\nEnable = False\r\n[ControlMapping]\r\nCross = CUSTOM\r\n";
  string preset=PpssppSettings.Preset(original,true,true);Assert(Setting(preset,"Graphics","InternalResolution")=="8"&&Setting(preset,"Graphics","MultiSampleLevel")=="2","8x internal resolution and 4x MSAA use official INI values");Assert(Setting(preset,"Graphics","VerticalSync")=="True"&&Setting(preset,"Graphics","ReplaceTextures")=="True"&&Setting(preset,"General","EnableCheats")=="True","VSync replacement and cheat menu enabled");Assert(Setting(preset,"Sound","Enable")=="False"&&Setting(preset,"Graphics","RenderingMode")=="9"&&Setting(preset,"ControlMapping","Cross")=="CUSTOM","unrelated audio graphics and controls preserved");Assert(Regex.Matches(preset,@"(?m)^InternalResolution =").Count==1,"no duplicate setting key");
  var cfg=new Settings{DataRoot=Path.Combine(w,"integration","data"),Memstick=Path.Combine(w,"integration","memstick"),BaseVersion="v8e"};string settings=Path.Combine(w,"integration","settings.json");var engine=new Engine(cfg,settings,tools);engine.RunningCheck=()=>false;engine.Progress=(message,percent)=>{if(!message.StartsWith("다운로드"))Console.WriteLine(message);};
  string cache=Path.Combine(cfg.DataRoot,"downloads",r.Tag);Directory.CreateDirectory(cache);foreach(var a in new[]{r.Base,r.Ui}.Concat(r.Hd)){string dest=Path.Combine(cache,a.Name);if(!File.Exists(dest))throw new Exception("Seed cache first: "+dest);}
  string psp=Engine.PspRoot(cfg.Memstick),system=Path.Combine(psp,"SYSTEM"),textures=Path.Combine(psp,"TEXTURES","NPJH50247");Directory.CreateDirectory(system);File.WriteAllText(Path.Combine(system,"ppsspp.ini"),original);File.WriteAllText(Path.Combine(system,"controls.ini"),"[ControlMapping]\r\nCross = CUSTOM\r\n");
  var missing=new Engine(new Settings{DataRoot=Path.Combine(w,"no-memory"),BaseVersion="v8e"},Path.Combine(w,"nm.json"),tools);missing.RunningCheck=()=>false;Reject(()=>missing.Install(r,false,false,false,false,true),"메모리스틱","UI requires selected profile");
  Reject(()=>engine.Install(r,false,false,false,false,true),"HD 고화질","UI without HD rejects before writes");Assert(!Directory.Exists(textures),"missing HD rejection writes no live textures");
  engine.Install(r,false,true,false,false);Assert(cfg.HdVersion=="HD-v39"&&cfg.UiVersion==""&&Engine.Hash(Path.Combine(textures,"textures.ini"))==r.HdIniHash,"HD only retains exact original-English UI");Assert(File.ReadAllText(Path.Combine(system,"ppsspp.ini"))==original,"global PPSSPP configuration unchanged");string gameIni=Path.Combine(system,"NPJH50247_ppsspp.ini");Assert(Setting(File.ReadAllText(gameIni),"Graphics","InternalResolution")=="8"&&cfg.GraphicsDefaultsApplied,"HD install creates requested game-specific defaults");
  string sentinel=Path.Combine(textures,"unrelated-user.txt");File.WriteAllText(sentinel,"keep");
  engine.Install(r,false,false,false,false,true);Assert(Engine.Hash(Path.Combine(textures,"textures.ini"))==r.UiKoreanHash&&cfg.UiVersion==r.UiVersion,"UI add-on changes only the selected component");Assert(File.ReadAllText(sentinel)=="keep","standalone UI install preserves unrelated user files");Assert(Directory.GetFiles(textures,"textures.ini.fate-backup-*").Any(p=>Engine.Hash(p)==r.HdIniHash),"previous original-English map backed up");
  engine.Install(r,false,false,false,false,false,true);Assert(Engine.Hash(Path.Combine(textures,"textures.ini"))==r.HdIniHash&&cfg.UiVersion=="","UI removal returns exact original high-resolution map");Assert(File.ReadAllText(sentinel)=="keep","UI removal preserves unrelated file");
  engine.Install(r,false,false,true,false);string cheats=Path.Combine(psp,"Cheats","NPJH50247.ini");Assert(Setting(File.ReadAllText(gameIni),"General","EnableCheats")=="True","cheat installation enables the PPSSPP cheat menu");Assert(Regex.Matches(File.ReadAllText(cheats),@"(?m)^_C0 ").Count==19&&!Regex.IsMatch(File.ReadAllText(cheats),@"(?m)^_C[12] "),"all 19 individual cheat codes remain disabled");Assert(!Directory.Exists(Path.Combine(psp,"SAVEDATA")),"unchecked clear save never installed");
  engine.Install(r,false,true,false,false,true);Assert(Engine.Hash(Path.Combine(textures,"textures.ini"))==r.UiKoreanHash&&cfg.UiVersion==r.UiVersion,"HD and UI install together");
  engine.Install(r,false,true,false,false);Assert(Engine.Hash(Path.Combine(textures,"textures.ini"))==r.UiKoreanHash&&cfg.UiVersion==r.UiVersion,"HD-only update preserves previous explicit UI opt-in");
  cfg.UiVersion="";cfg.HdVersion="HD-v40";engine.Install(r,false,false,false,false,false,true);Assert(Engine.Hash(Path.Combine(textures,"textures.ini"))==r.HdIniHash&&cfg.HdVersion==r.HdVersion,"legacy integrated v40 returns to original HD without full download");
  string old=File.ReadAllText(Path.Combine(textures,"textures.ini"));File.AppendAllText(Path.Combine(textures,"textures.ini"),";custom map\n");Reject(()=>engine.Install(r,false,false,false,false,true),"지원하는 HD 매핑","unknown customized map rejected instead of overwritten");Assert(File.ReadAllText(Path.Combine(textures,"textures.ini")).EndsWith(";custom map\n"),"custom map preserved");File.WriteAllText(Path.Combine(textures,"textures.ini"),old,new System.Text.UTF8Encoding(false));
  FileStream held=null;engine.Progress=(message,percent)=>{if(message.StartsWith("설치 적용 중"))held=new FileStream(gameIni,FileMode.Open,FileAccess.Read,FileShare.Read);};string oldSettings=Json.Serializer().Serialize(cfg);bool failed=false;try{engine.Install(r,false,false,false,false,true);}catch(IOException){failed=true;}finally{if(held!=null)held.Dispose();}
  Assert(failed&&Engine.Hash(Path.Combine(textures,"textures.ini"))==r.HdIniHash,"failure after map swap rolls texture map back");cfg=engine.Config;Assert(Json.Serializer().Serialize(cfg)==oldSettings&&!File.Exists(Path.Combine(cfg.DataRoot,"install-journal.json")),"failed install restores settings and clears journal");
  engine.Progress=null;engine.Cancel=new CancellationToken(true);Reject(()=>engine.Install(r,false,false,false,false,true),"취소","cancelled UI install exits before mutation");engine.Cancel=CancellationToken.None;
  string modified=PpssppSettings.Set(File.ReadAllText(gameIni),"Graphics","InternalResolution","3");File.WriteAllText(gameIni,modified);engine.ConfigureDefaults();Assert(Setting(File.ReadAllText(gameIni),"Graphics","InternalResolution")=="8"&&Setting(File.ReadAllText(gameIni),"General","EnableCheats")=="True","settings-only action restores graphics preset and existing cheat menu");
  Assert(File.ReadAllText(Path.Combine(system,"ppsspp.ini"))==original&&Regex.Matches(File.ReadAllText(cheats),@"(?m)^_C0 ").Count==19,"settings-only action preserves global configuration and all cheat toggles");
  using(var form=new LauncherForm(Path.Combine(w,"form-structure"),true)){var flags=BindingFlags.NonPublic|BindingFlags.Instance;var type=form.GetType();var ui=(System.Windows.Forms.CheckBox)type.GetField("uiBox",flags).GetValue(form);Assert(!ui.Checked&&ui.Text=="UI 한국어화","launcher exposes UI choice unchecked by default");Assert(type.GetField("uiRemove",flags).GetValue(form)!=null&&type.GetField("graphics",flags).GetValue(form)!=null,"launcher exposes UI restoration and graphics actions");}
  Json.Write(Path.Combine(w,"optional-ui-tests.json"),new{status="PASS",tests=count,real_archive_install=true,user_profiles_untouched=true,computer_use=false,runtime_game_retest=false});
 }
}
